### ISSUE TITLE
HTTP POST request body is null when attempting login

### ISSUE THREAD

**Issue by ArnoldPR** [ralscha/webauthn-demo#4]
Hello, I hope this message finds you well. I have a question regarding the following, when making an HTTP POST request for login using Angular, the request body seems to be null instead of containing the username. Can you please provide some clarification or assistance?

## Relevant Code
`this.httpClient.post<AssertionStartResponse>('assertion/start', null)
  .subscribe({
    next: response => this.handleAssertionStart(response),
    error: () => {
      loading.dismiss();
      this.messagesService.showErrorToast('Login failed');
    },
    complete: () => loading.dismiss()
  });
`

Thank you

**Comment by ralscha** [comment]
This demo does not only use passwordless but also usernameless login. The login page only shows a button.
This demo utilizes discoverable WebAuthn credentials (passkeys). In this mode, the private key is stored on the client's device together with the domain. To start with the login (assertion), the client only requires a random challenge from the server. This is why the body of the assertion/start request is empty. 

The client then uses the private key for this domain to sign the challenge and sends it back to the server together with the ID of the key pair. The public key is stored under the same ID on the server, so the server can look up the public key with this ID, verify the signature, and allow or deny the login. Because the credentials table with the public key has a reference to the app_user table the system knows what user it is.

While you don't need a username for discoverable WebAuthn credentials, in this demo the registration phase still requires the user to enter a username. That's because the string the user enters there is stored together with the domain and private key on the client's device. This is helpful when somebody has more than one account for the same domain. When the user logs in, the browser shows the user a list of credentials for this domain with the string he entered during the registration phase. This helps the user to select the proper credential.

On the server you don't need a username. This demo stores the username in the table app_user and also checks the the uniqueness. You could delete this field in the database it's not required. 
I think my idea was to store the email as username. This way the application has a way to contact the user, but it's not required for the login.


If you want to use non-discoverable credentials you need an unique id for the user, because the client only stores a master key and the server has to send the credential for this user to the client in the assertion/start phase. In this mode you have to send an username in the body of the request.
https://docs.turnkey.com/passkeys/discoverable-vs-non-discoverable#non-discoverable-credentials

**Comment by ArnoldPR** [comment]
I want to express my sincere gratitude for your help @ralscha . I now understand clearly how this demo works, and I must say that I greatly appreciate the excellent job you have done. I had a small doubt, but thanks to your explanation, it has been completely resolved. **Greetings**!
